### ISSUE TITLE
OnTwitterShow funtion

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#10]
Can you add an option field for actions after twitter shows up?
Is it also posible to ad this option before & after the embedJS has started? (before apply/ after apply)

              onTwitterShow:function(){
                  $('.column').matchHeight();
              },
              onEmbedJSLoad:function(){
                  $('.column').matchHeight();
              },
              onEmbedJSLoaded:function(){
                  $('.column').matchHeight();
              },

**Comment by ritz078** [comment]
What is the difference between onEmbedLoad and onEmbedLoaded ?

**Comment by comtronix** [comment]
EmbedLoad: actions efore the conversion of the content
EmbedLoaded: actions after the conversion of the content

**Comment by ritz078** [comment]
The functions are named
```javascript
//function to execute before embedding services
beforeEmbedJSApply: function () {},
 //callback after embedJS is applied
 afterEmbedJSLApply: function () {},
 //callback after all the twitter widgets are loaded.
 onTwitterShow     : function () {}
```

Currently in the canary branch .Will be merged with master once some other planned features are added.

**Comment by comtronix** [comment]
Merci! You are the best!

**Comment by ritz078** [comment]
You are helping a lot in making this plugin better . Thanks for that. :smile:
