### ISSUE TITLE
Some emojis not displaying properly.

### ISSUE THREAD

**Issue by profound7** [ritz078/embed.js#103]
Some emojis does not display properly. I generated all the emojis and ran it through EmbedJS. This is the screenshot (the emoji strings are taken from embed.js source itself).

![emoji](http://i.imgur.com/VVEBwVi.png)

What's causing some of these emojis to fail?

**Comment by ritz078** [comment]
can you create a demo on codepen ?

**Comment by profound7** [comment]
Switching the css source on codepen to https://cdn.jsdelivr.net/embed.js/3.6.2/embed.min.css causes that output. Funny thing is, when I downloaded the latest from git, and used dist/embed.min.css (hosted on my server), I get the weird output, but when I linked externally to https://rawgit.com/ritz078/embed.js/master/dist/embed.min.css it displays ok, even though they're the same file.

**Comment by ritz078** [comment]
It seems there was some error with css on jsdelivr. I have released an updated version which should fix this error.

**Comment by ritz078** [comment]
The new version on jsdelivr in working fine now.
