### ISSUE TITLE
Return promise from render or allow pass callback to options.

### ISSUE THREAD

**Issue by turboMaCk** [ritz078/embed.js#111]
Related with this (I better report this myself).
https://github.com/turboMaCk/Babylon-Grid/issues/7

I'm missing callback/promise in plugin api. Because of this it is not possible to run function after embed.js rendered DOM.

IMHO best possible implementation is using promises:

```js
ejs.applyEmbedJS(".embed").then(resetSomethig);
function resetSomethig.....
```

**Comment by ritz078** [comment]
I agree that this will be a better implementation . Till then you can use the option `afterEmbedJSApply` in the options object.

```js
afterEmbedJSApply : function(){}
```

**Comment by turboMaCk** [comment]
OH THX. I must missed this in documentation. In this case this will work perfectly. Thank you.
