### ISSUE TITLE
Global/window variables everywhere even when using npm?

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#121]
In https://github.com/ritz078/embed.js/blob/master/src/embed.js:

```js
window.ejs = { ...
window.fetchJsonp = fetchJsonp;
window[callbackFunction] = function (response)
window.regeneratorRuntime = regeneratorRuntime$1;
window.EmbedJS = EmbedJS;
```

IMHO this is not how a modern library must be designed (even more when it is supposed to be suitable for `npm` in which there MUST NOT be global variables).

Please, don't pollute the global `window` namespace with lot of uncontrolled global variables.

**Comment by ritz078** [comment]
You are right. I have fixed these in v4 that is currently in dev.

**Comment by ibc** [comment]
I suggest making the library to expose a single `embed` object with all those stuff that currently are made global. Then include `browserify` in the Grunt `dist` task with a option `{ standalone: 'embed' }`, and then use the browserified bundle file as "exported" file for bower or legacy `<script>` tag library loading mechanism.

That is a all-win since:

* Users loading embed via a legacy `<script>` tag will find `window.embed` and could use `var x = new embed.EmbedJS(...)`, etc.
* Users of NPM can do `var embed = require('embed-js')` and then `var x = new embed.EmbedJS(...)`, etc.

**Comment by ibc** [comment]
> You are right. I have fixed these in v4 that is currently in dev.

wow, sorry, I didn't read it. Will check 4.0.0 then.

Thanks a lot.

**Comment by ibc** [comment]
I'm checking source code of [v4](https://github.com/ritz078/embed.js/blob/feat/v4/src/embed.js). Indeed there is no `window.EmbedJS = EmbedJS;` but there are still lot of global variables.

For example, you are using `window` as a container for event listeners:

```js
      return new Promise(function (resolve, reject) {
          var callbackFunction = generateCallbackFunction();

          window[callbackFunction] = function (response) {
```

Since all the lib is generated within the closed/private scope of a function (line 14 of the code) you can perfectly create a local object/map and use it for those event listeners:

```js
// line 15:
var callbackFunctions = {};

// later:
      return new Promise(function (resolve, reject) {
          var callbackFunction = generateCallbackFunction();

          callbackFunctions[callbackFunction] = function (response) {
```

Same for `window.fetchJsonp = fetchJsonp;` (line 628)

**Comment by ritz078** [comment]
All the issues and solutions that you mentioned are already taken care of in v4.

Only one variable is exposed `EmbedJS`.

you can check the branch [here](https://github.com/ritz078/embed.js/tree/feat/v4). There will be some breaking changes.

**Comment by ibc** [comment]
Yes, that is the branch I'm inspecting, and yet I see `window.fetchJsonp = fetchJsonp;` and `window[callbackFunction] = function (response)` and all what I told in my previous comment.

Do I miss something? Thanks.

**Comment by ritz078** [comment]
fetchjsonp is an external library. I will try to send PR for that so that it is solved for everyone. If you want you can do that. I will make sure its fixed before release or else i will write my own and publish on npm.

**Comment by ritz078** [comment]
`window[functionName]` is needed as caalback functions lookfor them in the global scope. Removed `window.fetchJsonp = fetchJsonp`
