### ISSUE TITLE
Excel file support

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#13]
Option to show .xls or .xlsx files to view. (Like PDF option)

**Comment by ritz078** [comment]
Some breaking changes in the options are 

```javascript
docEmbed          : true,
      docOptions        : {
              viewText    : '<i class="fa fa-eye"></i> View PDF',
              downloadText: '<i class="fa fa-download"></i> DOWNLOAD'
      },
//callback before doc preview
      beforeDocPreview  : function(){},
      //callback after doc preview
      afterDocPreview   : function(){}
```

**Comment by comtronix** [comment]
THN! I cant get PPTx get to work. Local the file is ok. Xlsx Docx Pdf works fine! Very nice.

Then found a 'mug'

When posting link without http:// is does not convert to an embed.js item
I think http:// is required to recognize..?

**Comment by comtronix** [comment]
When i use the link 
https://docs.google.com/viewer?embedded=true&url=http://to.my.site/powerpoint.pptx
it works.
in embed.js the content cant be displayed

**Comment by ritz078** [comment]
it requires http:// or https://

**Comment by comtronix** [comment]
ok boss :P
