### ISSUE TITLE
Don't require global dependencies (window.marked, etc)

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#131]
When using CommonJS (browserify) I don't want to add a separate `<script>` tag for `marked.js` but instead:

```js
var marked = require('marked');
var embed = require('embed');
```

But that won't work (unless `marked` pollutes the global namespace `window` by adding `window.marked` which is 100% undesirable). That is because of this:

```js
if (!window.marked) throw new ReferenceError('marked.js is not loaded.');
```

I suggest that `embed` provides an API so the user/app can provide it with external dependencies, something such as:

```js
var marked = require('marked');
var embed = require('embed');

embed.set('marked', marked);
```

Or embed.js could try that internally:

```js
// if commonjs (require stuff) detected:
var marked = null;
try {
  marked = require('marked');
} catch (error) {
  marked = window.marked;
}

// [...]

if (!marked) throw new ReferenceError('marked.js is not loaded.');
```

**Comment by ritz078** [comment]
You may check now. now you can add them in options : 

```js
plugins                : {
	marked     : marked,
	videojs    : videojs,
	highlightjs: hljs,
	prismjs    : Prism,
	twitter    : twttr
},
```

**Comment by ibc** [comment]
:cake:
