### ISSUE TITLE
Cannot disable emoji/fontIcons

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#136]
```js
var x = new embed(
{
	input       : elem,
	link        : true,
	linkOptions :
	{
		target    : 'blank'
	},
	emoji       : false,
	fontIcons   : false
});

x.render();
```

However when `elem` contains something like `;)` its content is converted to:

```html
<span class="icon-emoticon" title=" ;) "></span>
```

Do I miss something?

**Comment by ibc** [comment]
I also miss a better explanation regarding `emoji` and `fontIcons`, which currently is just:

> ### emoji
>
Type : Boolean 
Default : true
Set to false if you want to disable converting emoji codes into actual emojis.
>
> ### fontIcons
>
Type : Boolean 
Default : true

**Comment by ritz078** [comment]
I am updating the docs.

Can u create a codepen demo to demonstrate the issue ? You can fork [this](http://codepen.io/ritz078/pen/JYmJML)

**Comment by ibc** [comment]
Such a codepen does not work:

```js
pen.js:33 Uncaught ReferenceError: EmbedJS is not defined
```

**Comment by ritz078** [comment]
Its working great for me. Maybe its a cdn issue.
![image](https://cloud.githubusercontent.com/assets/5389035/13082918/b7aba556-d4f8-11e5-879e-597d9358f9cb.png)

**Comment by ibc** [comment]
Sorry, it worked once I disabled "Privacy Badger" chrome extension for the site.

**Comment by ibc** [comment]
Done. Changes:

* Don't load https://rawgit.com/ritz078/embed.js/feat/v4/dist/_embed.min.css
* Don't put `<p>` tag in the `input` element.

http://codepen.io/anon/pen/KVEjop

**Comment by ritz078** [comment]
Set fontIcons to false in your example and i don't see the bug.

`:)` remains as ':)'

**Comment by ibc** [comment]
sorry, it works now (even in my own code) by setting `fontIcons: false`, not se what happened before...

**Comment by ibc** [comment]
Thanks a lot. Let's close this issue and sorry for the wasted time.

**Comment by ritz078** [comment]
no problem
