### ISSUE TITLE
Where to put assets/css?

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#141]
I just don't want to have an `assets` dir in my project root folder, nor I want to place `embed.css` into my non existing `MY_PROJECT/css/` folder.

`embed.css` includes paths as follows:

```css
.emoticon {
  background: transparent url(.././assets/images/emojis.png) 0 0 no-repeat;
}
```

So I expect that a tree like the following should work:

```
MY_PROJECT/
    resources/
        embed/
            src/
                embed.css
            assets/
                fonts/
                images/
```

Now the problem is that I use LESS in my project, producing a single  `MY_PROJECT/myproject.css` file that includes CSS namespaces to avoid style conflicts with the rest of the website (let's say this is a pluggable widget). If I embed `embed.css` into my LESS its links would then point to `../MY_PROJECT/`  which is just wrong.

Does embded provide some custom building mechanism to handle these cases?
Thanks a lot.

**Comment by ritz078** [comment]
Why even do this manually ?  Thats the reason we use `npm` or `bower`. What you are saying is something like css modules in webpack. If you use webpack even that can be done. 

I would still say that you should either use *cdn*, *npm* or *bower*

**Comment by ibc** [comment]
I do use npm, but npm is not good for resources (depending on the npm version, dependencies can be placed in `node_modules/` or a subdir inside it).

I don't want to do this manually. Of course I would code a gulp task to automatize it. My question is just regarding the relative path of the generated icon/images resources (given that I won't use the `embed.css` file as it is).

**Comment by ritz078** [comment]
You can change the destination path of css in gruntfile.js and run the corresponding `grunt` task.

**Comment by ibc** [comment]
Thanks. Since I wouldn't like to manage my own "fork" or copy of the whole `embed` project, I plan to add a gulp task within my project that mangles the relative path in `node_modules/embed-js/src/embed.css` and then copy it to my project `resources/` dir along with `assets`. I hope I don't miss nothing. Will check :)

Thanks.

**Comment by ibc** [comment]
Works great :+1:
