### ISSUE TITLE
[v4] Error with github URLs

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#142]
I've not yet applied latest cmmit https://github.com/ritz078/embed.js/commit/8cb52a8369e33aa3621a42b5449d74d63dd65d9a, but I don't think this is related.

"Sometimes" (50% of them) when I paste a Github URL I get this error:

`Uncaught (in promise) TypeError: Cannot read property 'avatar_url' of undefined`

For example this one:

https://github.com/versatica/jssip/issues

It happens here:

```js
key: 'github',
value: function github(data, options) {
	return '<div class="ejs-embed ejs-github"><div class="ejs-ogp-thumb" style="background-image:url(' + data.owner.avatar_url + ')"></div><div class="ejs-ogp-details"><div class="ejs-ogp-title"><a href="' + data.html_url + '" target="' + options.linkOptions.target + '">' + data.full_name + '</a></div><div class="ejs-ogb-details">' + data.description + '</div><div class="ejs-github-stats"><span><i class="fa fa-star"></i>' + data.stargazers_count + '</span><span><i class="fa fa-code-fork"></i>' + data.network_count + '</span></div></div></div>';
}
```

My usage is:

```js
var x = new embed(
{
	input       : paragraphElem,
	link        : true,
	linkOptions :
	{
		target    : 'blank'
	},
	emoji       : true,
	fontIcons   : true
});
```

I don't want special stuff for Github links, should I disable something? I don't find anything in the doc. Well, I see this:

```js
 openGraphExclude : ['youtube', 'github'],
```

but nowhere it is explained what `github` is...

**Comment by ibc** [comment]
Ok, similar error if I write a youtube URL...

`Uncaught (in promise) TypeError: Cannot read property '0' of undefined(…)`

**Comment by ibc** [comment]
I've set `openGraphExclude : ['youtube', 'github'],` and get the same issues... What should I disable to avoid these problems?

**Comment by ritz078** [comment]
I think this should help http://codepen.io/ritz078/pen/rxbGQE

**Comment by ibc** [comment]
Please, just remove `inlineEmbed:'all'` and see what happens (also open the browser console)

**Comment by ritz078** [comment]
check now.

**Comment by ibc** [comment]
It fixes the github problem. The youtube one remains:

http://codepen.io/anon/pen/MKROpW

```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at https://rawgit.com/ritz078/embed.js/feat/v4/dist/embed.min.js:10:13192
```
