### ISSUE TITLE
[v4] Remove calc() from CSS

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#143]
Hope images are self explanatory:

<img width="1157" alt="captura de pantalla 2016-02-17 a las 16 40 32" src="https://cloud.githubusercontent.com/assets/16191/13114809/63607218-d595-11e5-9068-15d80e7591af.png">

And them manually disabling the annoying `width: calc(-100%);`:

<img width="985" alt="captura de pantalla 2016-02-17 a las 16 41 17" src="https://cloud.githubusercontent.com/assets/16191/13114819/74c2fa9e-d595-11e5-9962-0868908f2b59.png">

**Comment by ritz078** [comment]
fixed
