### ISSUE TITLE
[v4] excludeEmbed: 'all' does nothing

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#144]
http://codepen.io/anon/pen/MKROBK

**Comment by ibc** [comment]
To be absolutely clear: after reading the full documentation and spending some hours with it, I have no idea regarding how to disable all the embed content. Let's say for now I just want emojis and fontIcons (already working) and any HTTP link (also working, all but Youtube links due to #142), and I don't want anything else (no embed videos, no embed github, etc).

**Comment by ritz078** [comment]
I am already aware of that. Why do you think v4 is not released yet ? You are using a version which is still in development.

**Comment by ibc** [comment]
Clear :)

**Comment by ibc** [comment]
Thanks. Already tested yesterday :)
