### ISSUE TITLE
No Promise polyfill when using browserify

### ISSUE THREAD

**Issue by ibc** [ritz078/embed.js#146]
`var embed = require('embed-js');` returns `src/embed.js` which does not load the `es6-promise` dependency. In fact, such a dependency is not used at all in the whole "v4" code.

Shouldn't `src/embed.js` load it?:

```js
var Promise = require('es6-promise');

[...]
```

**Comment by ritz078** [comment]
There may be the condition when the user may use RequireJS and would like to load `es6-promise` only when it is not present in the browser. So I will rather leave it to the user to load it in the way he/she wants. But I should definitely update the documentation regarding this. 

At the same time, I am open to load this internally if someone can convince me that it will be better.
