### ISSUE TITLE
Gist support not working

### ISSUE THREAD

**Issue by exexzian** [ritz078/embed.js#147]
Tried with your sample example as well for gist support but it is not working as expected.

[http://codepen.io/ritz078/pen/gaNEYJ](http://codepen.io/ritz078/pen/gaNEYJ)

**Comment by ritz078** [comment]
Hi @exexzian ,

I am aware of this. It has been fixed in v4 that is currently merged in master. I am just busy writing docs for that and will release it in few days. You can use the v4 code and if you find any issue let me know here until the new docs are published .

**Comment by exexzian** [comment]
thanks for the update @ritz078 .

Checked the updated example and v4 and yup it works fine.
