### ISSUE TITLE
Button text

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#15]
Option for labeling the buttons in Embed.js (example : view/download button for PDF)
or option to include a special embed_language_en.js file or something.

english can be default language if nothing is included

**Comment by ritz078** [comment]
Now there are two options
```javascript
pdfOptions        : {
              viewText    : '<i class="fa fa-eye"></i> View PDF',
              downloadText: '<i class="fa fa-download"></i> DOWNLOAD'
      },
```

**Comment by comtronix** [comment]
Thnx  2 :P please check your Gmail!
