### ISSUE TITLE
Uncaught (in promise) TypeError: Invalid attempt to destructure non-iterable instance(…)

### ISSUE THREAD

**Issue by alantliang** [ritz078/embed.js#153]
Hi, I'm trying to use embed.js in a meteor.js application. I've called 
```
require('es6-promise').polyfill();
import EmbedJS from 'embed-js';
```

and I've copied the div and js code from the youtube example, however I receive the error: 

> Uncaught (in promise) TypeError: Invalid attempt to destructure non-iterable instance(…)

I'm curious if you have received this error before and if you know what steps I can take to resolve this issue. Thanks!

**Comment by ritz078** [comment]
Can you provide the whole error stack ? That will help

**Comment by alantliang** [comment]
Hey ritz, thanks for the reply. I have a misconfiguration issue and I'll let you know if I run into further problems.
