### ISSUE TITLE
Github code don't work

### ISSUE THREAD

**Issue by kamov** [ritz078/embed.js#154]
Hi,

I am trying to make this example work:
http://codepen.io/ritz078/pen/gaNEYJ

But I get an error that git is not found. I am using the same git that you are using.

```js
    ejs.setOptions({
      inlineEmbed:'all',
      googleAuthKey : 'AIzaSyCewriFcx-XXXXXX_WiTzMYF0hf8'
    });

    ejs.applyEmbedJS('.text');
```

and only this js:

```js
<script src="https://cdn.jsdelivr.net/embed.js/3.6.2/embed.min.js" /></script>
```

and of course your css.

this is error:
![screen shot 2016-04-09 at 08 55 25](https://cloud.githubusercontent.com/assets/2345000/14402286/0d1fcd12-fe31-11e5-8b1b-bb0acc7f2cfe.png)

Git link used: 
⁣https://gist.github.com/ritz078/c4e08840344f1d9e8267

Thanks!

**Comment by kamov** [comment]
I get now below error 403:

![screen shot 2016-04-09 at 09 09 39](https://cloud.githubusercontent.com/assets/2345000/14402333/deb34010-fe32-11e5-9a5d-71ada83d264c.png)

**Comment by ritz078** [comment]
Fixed in v4. That codepen demo uses v4. But there are some breaking changes so keep a watch on them.

**Comment by kamov** [comment]
Thanks! I will check again.
