### ISSUE TITLE
Add new line

### ISSUE THREAD

**Issue by kamov** [ritz078/embed.js#155]
Hi,
when I try to add markdown code, then embed don't covert new line to br, so all code appear in one line.
I add: 

![screen shot 2016-04-09 at 09 04 19](https://cloud.githubusercontent.com/assets/2345000/14402314/2ec27234-fe32-11e5-9816-0c2b90023120.png)

But then is show as:
![screen shot 2016-04-09 at 09 03 47](https://cloud.githubusercontent.com/assets/2345000/14402316/366f7c02-fe32-11e5-9c15-fc3be091e093.png)

I don't see on your example that you add new line (BR) tag, but only space between text.

Is missing something?
Thanks

**Comment by kamov** [comment]
This is how appear your example of markdown:

![screen shot 2016-04-09 at 09 06 28](https://cloud.githubusercontent.com/assets/2345000/14402319/693def88-fe32-11e5-8b6a-064fd7863cc5.png)

**Comment by ritz078** [comment]
[this](http://codepen.io/ritz078/pen/bVmPrX) is my example of markdown and its working fine. Here a [fork](http://codepen.io/ritz078/pen/LNQPEd) that addresses your new line issue. I hope these help.

**Comment by kamov** [comment]
Thanks! I will try again tomorrow.
