### ISSUE TITLE
Emojione support

### ISSUE THREAD

**Issue by kamov** [ritz078/embed.js#156]
I am using http://emojione.com/
And I have already code for convert emoji shortname.

Can this make some issue?
Do you think to integrate emojione since is good project?
Thanks

**Comment by ritz078** [comment]
I am not sure about this. Adding support for 3rd party plugins for features that are already present in embed.js will just increase the file size with no additional output.

**Comment by kamov** [comment]
I understand. Because I use one emoji picker that use emojione, for this reason.
Do you update your emoji icon?
Does this support also emoji added via mobile?

**Comment by kamov** [comment]
On readme, under section "Adding custom emojis"
there is a link example adding new emoji, but page not found...
