### ISSUE TITLE
LocationEmbed function option request

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#16]
Function to choose MAP of streetview or combination of both in a box

**Comment by ritz078** [comment]
Streetview needs the exact coordinates of the location and I don't think people will be writing something like @(12.12,14.54) in the normal text.

**Comment by comtronix** [comment]
Mabey you can use this to convert adres to coordinates:


<script>

var latitude;
var longitude;

/*
* Get the json file from Google Geo
*/
function Convert_LatLng_To_Address(address, callback) {
        url = "http://maps.googleapis.com/maps/api/geocode/json?address=" + address + "&sensor=false";
        jQuery.getJSON(url, function (json) {
            Create_Address(json, callback);
        });        
}

/*
* Create an address out of the json    
*/
function Create_Address(json, callback) {
    if (!check_status(json)) // If the json file's status is not ok, then return
        return 0;
    latitude = json["results"][0]["geometry"]["location"]["lat"];
    longitude = json["results"][0]["geometry"]["location"]["lng"];
    callback();
}

/* 
* Check if the json data from Google Geo is valid 
*/
function check_status(json) {
    if (json["status"] == "OK") return true;
    return false;
}


var address = "handelsstraat 70 stadskanaal";

Convert_LatLng_To_Address(address, AlertLatLng);     
function AlertLatLng() {
    var result = "The latitude is " + latitude + " and longitude is " + longitude;
    document.getElementById('result').innerHTML=result;
}

</script>

**Comment by comtronix** [comment]
[code]
var latitude;
var longitude;

/*
* Get the json file from Google Geo
*/
function Convert_LatLng_To_Address(address, callback) {
        url = "http://maps.googleapis.com/maps/api/geocode/json?address=" + address + "&sensor=false";
        jQuery.getJSON(url, function (json) {
            Create_Address(json, callback);
        });        
}

/*
* Create an address out of the json    
*/
function Create_Address(json, callback) {
    if (!check_status(json)) // If the json file's status is not ok, then return
        return 0;
    latitude = json["results"][0]["geometry"]["location"]["lat"];
    longitude = json["results"][0]["geometry"]["location"]["lng"];
    callback();
}

/* 
* Check if the json data from Google Geo is valid 
*/
function check_status(json) {
    if (json["status"] == "OK") return true;
    return false;
}


var address = "streetname number city";

Convert_LatLng_To_Address(address, AlertLatLng);     
function AlertLatLng() {
    var result = "The latitude is " + latitude + " and longitude is " + longitude;
    document.getElementById('result').innerHTML=result;
}

[/code]

**Comment by comtronix** [comment]
maybey you can use this converter to get the coord's.


var latitude;
var longitude;

function Convert_LatLng_To_Address(address, callback) {
        url = "http://maps.googleapis.com/maps/api/geocode/json?address=" + address + "&sensor=false";
        jQuery.getJSON(url, function (json) {
            Create_Address(json, callback);
        });        
}

function Create_Address(json, callback) {
    if (!check_status(json)) // If the json file's status is not ok, then return
        return 0;
    latitude = json["results"][0]["geometry"]["location"]["lat"];
    longitude = json["results"][0]["geometry"]["location"]["lng"];
    callback();
}

function check_status(json) {
    if (json["status"] == "OK") return true;
    return false;
}


Convert_LatLng_To_Address(address, AlertLatLng);     
function AlertLatLng() {
    var result = "The latitude is " + latitude + " and longitude is " + longitude;
    document.getElementById('result').innerHTML=result;
}

var address = "adres number city";

**Comment by ritz078** [comment]
How will you resolve the issue of multiple place with same name ? I don't think anyone is going to write the whole address.

**Comment by comtronix** [comment]
var address = "adres number city COUNTRY/REGION"; can be used too...

**Comment by ritz078** [comment]
now you can check them and report any bugs that you find.

**Comment by comtronix** [comment]
thnx. I updated the embed.js and added the options, but can't see a diference in the map display.

**Comment by ritz078** [comment]
what does your option look like ?

**Comment by comtronix** [comment]
i tried: 'place' or 'streetview' or 'view'

**Comment by ritz078** [comment]
are you using the latest code from the canary branch ?

**Comment by comtronix** [comment]
yes from this location
https://github.com/ritz078/embed.js/commit/6cdb951c8ae15563613f99b995c21d317a425907

**Comment by ritz078** [comment]
any error on the console ?

**Comment by comtronix** [comment]
i think i found the problem :P i was running script on old backup folder.
it works now.

sorry :(

**Comment by ritz078** [comment]
nice that ur problem is solved now :smile:

**Comment by comtronix** [comment]
yeah yeah! next time i look 4times before reporting something :P

**Comment by comtronix** [comment]
push the button to close this :P

**Comment by ritz078** [comment]
its already closed.
