### ISSUE TITLE
Change template of youtube, vimeo and google map

### ISSUE THREAD

**Issue by kamov** [ritz078/embed.js#162]
When there are many youtube video or vimeo or google map,
the loading become very slow.

I would like to change template of this and show only link of a lightbox.

For example this should be result:

```html

<!-- youtube -->
<a class="lightbox" href="https://www.youtube.com/embed/VIDEO-ID?autoplay=1">
<img src="http://img.youtube.com/vi/VIDEO-ID/0.jpg" alt="Youtube video"/>
</a>
<!-- vimeo -->
<a class="lightbox" href="https://player.vimeo.com/video/VIDEO-ID"><img id="vimeo-VIDEO-ID'" src="loaded from json" alt="Vimeo video"/></a>
<!-- google map -->
<a class="lightbox" href="http://maps.google.com/?output=embed&f=q&source=s_q&hl=en&geocode=&q=London+Eye,+County+Hall,+Westminster+Bridge+Road,+London,+United+Kingdom&hl=lv&ll=51.504155,-0.117749&spn=0.00571,0.016512&sll=56.879635,24.603189&sspn=10.280244,33.815918&vpsrc=6&hq=London+Eye&radius=15000&t=h&z=17">Google maps</a>

```

Can you show an example how to change template for this?

I have already integrated a lightbox plugin, I just need to set correct html as example show.

Thanks!

**Comment by ritz078** [comment]
```js
var template = EmbedJS.Template();
template.youtube = function(url, options){
  return new-template;
} //similar for vimeo
```

the google-map template is not yet implemented. I will do it soon.

**Comment by kamov** [comment]
Thanks! For google map, allow also to embed static map template because when there are many map on a page, take time to load. See: https://developers.google.com/maps/documentation/static-maps/intro#quick_example

**Comment by kamov** [comment]
How to setup template using static method?
If you can show me an example how to render, update during ajax and set template will be helpful.
At the moment I am stuck, I can't sort this out.
Thanks!

**Comment by ritz078** [comment]
Maybe [this](https://github.com/ritz078/embed.js/blob/master/src/js/main.js#L380) can help for static templating. Read the comment.

I will update the documentation.

**Comment by kamov** [comment]
Thanks for update documentation, more complete examples will be useful.
