### ISSUE TITLE
:+1: and :-1: emojis not working

### ISSUE THREAD

**Issue by syavash** [ritz078/embed.js#164]
I've checked the source code and it seems the problem is the Regex at https://github.com/ritz078/embed.js/blob/master/src/js/modules/regex.js#L28.

Following code returns `null`:
```
'Testing :+1: :-1:'.match(/(\:\w+\:|\<[\/\\]?3|[\(\)\\\D|\*\$][\-\^]?[\:\;\=]|[\:\;\=B8][\-\^]?[3DOPp\@\$\*\\\)\(\/\|])(?=\s|[\!\.\?]|$)/gi)
```
I think this regex will fix the issue:
```
/(\:[\+\-\w]+\:|\<[\/\\]?3|[\(\)\\\D|\*\$][\-\^]?[\:\;\=]|[\:\;\=B8][\-\^]?[3DOPp\@\$\*\\\)\(\/\|])(?=\s|[\!\.\?]|$)/gi
```

**Comment by ritz078** [comment]
fixed. Thanks
