### ISSUE TITLE
Using string instead of dom element is not working

### ISSUE THREAD

**Issue by Minstel** [ritz078/embed.js#167]
I'm trying to use string url for embeding as follows (using v4.0.3):
```
var link = 'https://www.youtube.com/watch?v=6-FawtEroEI';
var embed = new EmbedJS({input: link});

embed.text(function(result, input) {
//do smth
});
```

But I receive the following error:
`Uncaught (in promise) TypeError: this.options.input.addEventListener is not a function`.

I also tryed to use it in a way it should have worked in v3.x.x:
`var embed = new EmbedJS({}, link);`

But then I receive an error: 
`Uncaught ReferenceError: You need to pass an element or the string that needs to be processed`

**Comment by ritz078** [comment]
fixed in v4.0.4
