### ISSUE TITLE
responsive css 

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#17]
The display of PDF/Video is not nicely displayed on small devcies *phones* The PDF/Video becomes a box with sliders . 

@media only screen and (min-width: 480px) and (max-width: 767px) { }
@media only screen and (max-width: 479px) { }

**Comment by ritz078** [comment]
Can you post a screenshot ?

**Comment by comtronix** [comment]
![01](https://cloud.githubusercontent.com/assets/3840400/7095685/a34aa714-dfcc-11e4-8ba6-b91421ff91c6.jpg)

**Comment by comtronix** [comment]
Vines to width..
![02](https://cloud.githubusercontent.com/assets/3840400/7095716/db820a28-dfcc-11e4-9c99-e2929623e57b.jpg)

**Comment by comtronix** [comment]
![03](https://cloud.githubusercontent.com/assets/3840400/7095746/32e2ed82-dfcd-11e4-833b-541f70edc5ec.jpg)

**Comment by ritz078** [comment]
For vine there is an option to set its width .
Writing the pdf/video css based on the device width is not great always because sometimes that is not taking the full device width and is wrapped inside a div of somewhat lesser width than the device's width. That will create problems for the user.

So better you write your own css based on the div width in which you are using the plugin and not the device width.

**Comment by ritz078** [comment]
You can always add your css over the default one according to your needs. If you have some solution that will be consistent in all cases then only it can be implemented in the plugin.

**Comment by comtronix** [comment]
Thnx. fixed it by getting the class width and parsing it true embed.js

    var width = $('.forum').width();    
    var $window = $(window);           

    $window.resize(function resize(){
        var width = $('.forum').width();
    });

For the pdf and youtube i will create custom css for phones.

**Comment by ritz078** [comment]
Can you send a PR ?

**Comment by comtronix** [comment]
What is a PR :P

**Comment by ritz078** [comment]
Its Pull Request. see [this](https://help.github.com/articles/creating-a-pull-request/)

**Comment by comtronix** [comment]
Never did it before. Ill read is as soon as !

**Comment by ritz078** [comment]
Though your solution will work but i will have to include this responsiveness code inside the plugin as on each resize your code will reload the whole content. This means repeated http requests. Thats never good. I will see what i can do.

**Comment by comtronix** [comment]
can you also set in your next release the hight of the iframe fore VINE + 2 pixels? 158 seems te be to short for the last borderline from Vine
                    
str = str + '<div class="ejs-vine"><iframe src="https://vine.co/v/' + matches[i].split('/')[2] + '/embed/' + opts.vineOptions.type + '" height="' + (opts.vineOptions.type == 'postcard' ? (opts.vineOptions.width + 160) : opts.vineOptions.width) + '" width="' + opts.vineOptions.width + '"></iframe></div>';

**Comment by comtronix** [comment]
currently working on a iframe refresh after resize window:

$('.ejs-vine-iframe',window.parent.document).attr('src',$('.ejs-vine-iframe',window.parent.document).attr('src'));

**Comment by comtronix** [comment]
I default size is 500 for vine, and opening page with vine on smaller device the vinewidt is 500px.

resizing from large window to smaller works, vine shrinks too. but when resizing from very small to big window the vine does not resize bigger anymore,

maybey it's an solution to get the width of the element div and take a amount of pixels to lower the width. when resizing then always resize the vine box too.

**Comment by ritz078** [comment]
Actually here width that you set is **maxWidth** but i guess yours solution seems better .I will fix this
* When there is no width set it will take the width of whole div

**Comment by ritz078** [comment]
Now there are slight change in options
```javascript
vineOptions:{
            maxWidth:500,
            type:'postcard',         //'postcard' or 'simple' embedding
            responsive:false         // whether to make the vine embed responsive
      },
```
I guess you can understand the function about how it works. If not do reply here. I am closing this issue now.

**Comment by comtronix** [comment]
thank you for this :)
