### ISSUE TITLE
Video support example shows Google Map example

### ISSUE THREAD

**Issue by diegosouza** [ritz078/embed.js#176]
Hello,

First of all, I'd like to congratulate you for the project. I really like it.

Since I don't have a ReadMe.io account (and I don't want it), I'm opening this issue to warn about the duplication: [Video support example](https://embedjs.readme.io/docs/video-support) shows the same content from [Google Map example](https://embedjs.readme.io/docs/google-map) in the docs page.

**Comment by ritz078** [comment]
fixed.

**Comment by diegosouza** [comment]
Thank you @ritz078
