### ISSUE TITLE
Cant require(embed-js) in Node

### ISSUE THREAD

**Issue by pursual** [ritz078/embed.js#180]
var EmbedJS = require('embed-js');

Gives error

```
TypeError: Cannot read property 'fetch' of undefined
    at /xxx/node_modules/embed-js/src/embed.js:916:15
    at /xxx/node_modules/embed-js/src/embed.js:1299:7
```

**Comment by ritz078** [comment]
any chance I can see the code ?

**Comment by pursual** [comment]
That is the code so far. It fails as soon as I require. I haven't gotten past that point.

**Comment by ritz078** [comment]
I tried it and its working fine for me. are you sure you are using v4.1.4 ? maybe if I can see your code, I will be able to help or if its not possible lets discuss here.

**Comment by pursual** [comment]
I installed by npm and it seems to be 4.1.4. I was able to get it to work by setting self = {}; and commenting out the references to "window" in the default options. Its obviously not really meant to run in node. Like I said, there is no code for you to see. It fails on require because self is undefined.

**Comment by pursual** [comment]
Node doesnt have a "self" or "window" global...so your code wont work.

**Comment by ritz078** [comment]
of course this is not an isomorphic code. it will only run on client side :)

**Comment by pursual** [comment]
Yeah, just confusing that you use npm, which is mainly for node. I wanted to use it in Node with the .text() function.

**Comment by ritz078** [comment]
I will try to make this isomorphic.

**Comment by MaxLeiter** [comment]
being able to do server-side fetching would be awesome (esp. for caching)

**Comment by ritz078** [comment]
yes. for that i will also have to separate code that handles interactions like click, load etc. But that should be surely doable.

**Comment by niko-h** [comment]
I installed embedjs via `meteor npm install --save embed-js` and the module seems to be installed properly @4.1.13.
Requiring it via `import EmbedJS from 'embed-js';` does not work though. It gives me an 
> Uncaught Error: Cannot find module 'embed-js'
Any suggestions?

**Comment by ritz078** [comment]
If the error is that the module hasn't been found, it should be something specific to meteor. Someone with meteor experience may help.

**Comment by niko-h** [comment]
I guess some kind of meteor-wrapper-package would have to be written. Unfortunately I don't see myself up to this task. Thumbs up anyway for embed.js! Didn't find an alternative with as many supported embeds yet.

**Comment by ritz078** [comment]
@niko-h Can you open a separate issue so that I can try to fix this.

**Comment by ritz078** [comment]
isomorphic support available in v5 beta.
