### ISSUE TITLE
ReferenceError thrown if input is empty string

### ISSUE THREAD

**Issue by mschwartz** [ritz078/embed.js#181]
```
new EmbedJS({ input: '' })
```

throws exception.

**Comment by ritz078** [comment]
that is because you are passing an empty string.

**Comment by mschwartz** [comment]
Yes, but an empty string is valid.

You are using a falsy test on input:, and it should allow empty string.

maybe:

```if (input === '') { return ''; }``

**Comment by ritz078** [comment]
Agreed :)
