### ISSUE TITLE
More max-height and max-width support

### ISSUE THREAD

**Issue by MaxLeiter** [ritz078/embed.js#183]
Options for setting max-height and width of different embeds would be fantastic. I'll be making PRs over the next few weeks regarding this, would like to hear thoughts/criticisms

**Comment by ritz078** [comment]
For iframes, I think this will be beneficial as CSS won't work for them.

**Comment by ritz078** [comment]
V5 accepts separate height for all plugins. And CSS can be adjusted by using CSS.
