### ISSUE TITLE
Soundcloud generated URLs incorrect

### ISSUE THREAD

**Issue by MaxLeiter** [ritz078/embed.js#188]
example:

`https://w.soundcloud.com/player/?url=soundcloud.com/verkanntekunst/sets
		&auto_play     = false
		&hide_related  = false
		&show_comments = true
		&show_user     = true
		&show_reposts  = false
		&visual        = false
		&download      = false
		&color         = f50000
		&theme_color   = f50000`

The spaces are being URL-encoded

**Comment by MaxLeiter** [comment]
This started working

**Comment by MaxLeiter** [comment]
https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/200445688&auto_play%20%20%20%20%20=%20false&hide_related%20%20=%20false&show_comments%20=%20true&show_user%20%20%20%20%20=%20true&show_reposts%20%20=%20false&visual%20%20%20%20%20%20%20%20=%20false&download%20%20%20%20%20%20=%20false&color%20%20%20%20%20%20%20%20%20=%20f50000&theme_color%20%20%20=%20f50000

It renders correctly but the values passed aren't valid due to the above

**Comment by MaxLeiter** [comment]
The problem is uglify: 

		let url = `https://w.soundcloud.com/player/?url=${match}
		&auto_play     = ${config.autoPlay}`
-----------------
		var url = ('https://w.soundcloud.com/player/?url=' + match + '\n\t\t\t&auto_play     = ' + config.autoPlay + '\n\t\t\t'`

**Comment by MaxLeiter** [comment]
https://github.com/ritz078/embed.js/blob/master/src/embed.js#L265

**Comment by ritz078** [comment]
Sorry for the delay. I am just very busy these days so replies take time and fixes are a bit delayed.
