### ISSUE TITLE
Twitter widgets being duplicated

### ISSUE THREAD

**Issue by MaxLeiter** [ritz078/embed.js#189]
![image](https://i.imgur.com/kAxcYhO.png)

**Comment by ritz078** [comment]
What's the input string or the DOM content before applying the plugin ?

**Comment by MaxLeiter** [comment]
Just the Twitter URL

**Comment by ritz078** [comment]
I didn't find any issue. https://codepen.io/ritz078/pen/mAzLdB . Its working fine for me.

**Comment by MaxLeiter** [comment]
Sorry, was a promises issue
