### ISSUE TITLE
Bug found LiveLeak

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#19]
When i post a link of LiveLeak.com it's displaying 2 videos (same), i tested multiple vid links.
 http://www.liveleak.com/view?i=42a_1426999994

i am using your latest JS

**Comment by comtronix** [comment]
it happens when the link is posted like <a href"url"><link</a> only.

**Comment by comtronix** [comment]
i fixed it local before outputting de dbase content. (php)

**Comment by ritz078** [comment]
Great that you fixed the issue yourself but now i have fixed that in the plugin also. So no more duplicates will be shown for liveleak videos. :smile:

**Comment by comtronix** [comment]
i remove the tags first now.
 preg_replace('/<a href=\"(.*?)\">(.*?)<\/a>/', "\\2"

**Comment by comtronix** [comment]
o it was buggie also on your site?

**Comment by ritz078** [comment]
I forgot to remove the duplicates from liveleak array. So it was buggy for all. Now i have fixed that so even if it detects multiple links it won't process the duplicates.

**Comment by comtronix** [comment]
okay :)
