### ISSUE TITLE
Possible to return if an embed is found?

### ISSUE THREAD

**Issue by MaxLeiter** [ritz078/embed.js#190]
is there currently a way to check if an embeddable URL was found in the input? (Basically if embed.js actually did anything)?

**Comment by ritz078** [comment]
saving the nodes on which embed-js has been applied won't be a good idea. maybe adding a class or an attribute after the plugin has been applied can help.

**Comment by MaxLeiter** [comment]
The problem is the plugin is applied if a URL is found, but embeds doesn't embed normal websites (which is fine), so I want to handle those myself.

**Comment by MaxLeiter** [comment]
@ritz078 would you be against render() having a callback function returning the changes (not the result of the entire input, just the link(s) embedded?

` x.render(function(array)  { 
console.log(array[0]); // https://gist.github.com...
});`

**Comment by ritz078** [comment]
No I won't be against it. You can see this `data` which is passed in the callback of `.text()`.You can add another key in that object. We can do the same for `.render` which renders the content and return the similar callback as `.text()`

**Comment by ritz078** [comment]
Was this problem solved ?

**Comment by MaxLeiter** [comment]
No, I don't have time to get around to it /:

**Comment by ritz078** [comment]
In v5 a class "ejs-applied" is added to all the nodes processed by embed.js and if you try to re apply the plugin won't do anything.
