### ISSUE TITLE
Error parsing ustream URLs

### ISSUE THREAD

**Issue by Yonirt** [ritz078/embed.js#192]
It seems there is some kind of bug when try parsing the URLs from ustream.tv. 

Any help would be really appreciated.

Thanks!

Ex:  http://www.ustream.tv/embed/1041782

```
embed.js:2287 GET http://www.http/embed//www.ustream.tv/embed/1041782 net::ERR_NAME_NOT_RESOLVED
```

**Comment by ritz078** [comment]
any idea why `<iframe src="//www.ustream.tv/embed/1041782" height="540" width="720"></iframe>` isn't working ?

**Comment by Yonirt** [comment]
I dont' know :(
