### ISSUE TITLE
Hide the embedded url

### ISSUE THREAD

**Issue by Matoo125** [ritz078/embed.js#194]
Hello, this is beautiful plugin. I have one question. How can I hide the url of embedded video or picture?

Now I do it with class 'hidden' (display:none). I put every media link inside hidden paragraph and then it works as I want. I am just wondering if there is some build in option for that

**Comment by ritz078** [comment]
set `{inlineText: false}` in options.

**Comment by Matoo125** [comment]
thanks.

**Comment by Matoo125** [comment]
I tried it and have 2 problems.
1. If I embed 2 different videos for some reason it  embeds first video twice
2. if I click on video it opens video in the new tab and at the same time plays video on my page as it should

**Comment by ritz078** [comment]
Can you create a codepen demo by forking http://codepen.io/ritz078/pen/QjZded ? It will be helpful.

**Comment by Matoo125** [comment]
http://codepen.io/Matoo125/pen/rWRZZx
Here it is

**Comment by ritz078** [comment]
This is definitely a bug. Thanks for reporting.

**Comment by Matoo125** [comment]
good job. 

I downloaded version from npm, but i cannot see it embedding visual part, just text and description

https://s30.postimg.org/eibb4nd4h/Capture.png

**Comment by ritz078** [comment]
check with v4.1.12 and doc example seems to be working fine.

**Comment by Matoo125** [comment]
https://s28.postimg.org/wvk7f6nlp/Screenshot_from_2017_01_25_20_24_37.png
same in chrome / opera / firefox .. also opengraph and markdown looks the same.

downloaded again with npm and now it's working. Thank you, will make use of it :1st_place_medal:
