### ISSUE TITLE
emoji parsing issue

### ISSUE THREAD

**Issue by levgaas** [ritz078/embed.js#197]
When emoji aren't separated by a space only the last one is parsed

![image](https://cloud.githubusercontent.com/assets/10091564/21511293/8a09368e-cca7-11e6-9249-81735c705f85.png)

http://codepen.io/anon/pen/ZBdjqX

Thanks!

**Comment by levgaas** [comment]
changing regexp from `smileys: /(\:[\+\-\w]+\:|\<[\/\\]?3|[\(\)\\\D|\*\$][\-\^]?[\:\;\=]|[\:\;\=B8][\-\^]?[3DOPp\@\$\*\\\)\(\/\|])(?=\s|[\!\.\?]|$)/gi`
to `smileys: /(\:\w+\:)/gi`

Works for me. But I don't about concequences

**Comment by ritz078** [comment]
How about a PR ?
