### ISSUE TITLE
render() promise

### ISSUE THREAD

**Issue by levgaas** [ritz078/embed.js#201]
render() promise is fired when html is parsed. But can we get an actual callback when html is fully rendered?

For example, twitter example. Fully rendering appears after 0.5s render() promise is fired.

http://codepen.io/anon/pen/JEGjzj

Thanks!

**Comment by ritz078** [comment]
I will look into it.

**Comment by ritz078** [comment]
there's a `onTweetsLoad()` function in options thats fired when the tweets have loaded. You can try that.

**Comment by MaxLeiter** [comment]
How hard would a onEmbedLoad()? Just for all embeds not just twitter?

**Comment by ritz078** [comment]
Eventually I will want to change this library into plugin based and doing that will be tough. Anyways I don't think anything delays except twitter.

**Comment by ritz078** [comment]
in v5 twitter plugin is separate and it provides an `onLoad()` method that gets called when tweets are rendered.
