### ISSUE TITLE
Why removing dist folder ?

### ISSUE THREAD

**Issue by nept** [ritz078/embed.js#207]
In the version **4.1.11** and after this one, the **dist** folder has been removed from the project and also breaks the bower integration (no more dist or src folder with min files) ? Is it volunter ?

**Comment by ritz078** [comment]
Keeping dist on github isn't a nice pattern. It should work if you use npm. I will be removing bower support. But I agree that this was done by mistake.

**Comment by nept** [comment]
Yes, agree about the wrong pattern, but right now, no more js file of the project are available from a bower integration >= 4.1.11 and i just wanted to ask if this regression was know.
Indeed, it's time to delegate the gestion of this package to npm ;)

Thank's for you quick reply
