### ISSUE TITLE
Future request phpfiddle

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#21]
Output / include boxes like Jsfiddle. Here are 8 fiddles for developpers.
http://phpassist.com/

**Comment by comtronix** [comment]
this one hase even more http://www.tutorialspoint.com/codingground.htm

**Comment by ritz078** [comment]
Making all makes no sense. It will unnecessarily increase the plugin size .Its better if we include only the popular ones.

**Comment by comtronix** [comment]
i prefer PHP

**Comment by ritz078** [comment]
It will be great if you can list the popular ones for php. I am not too much into php.

**Comment by comtronix** [comment]
js angular (also works in fiddle?):
http://www.tutorialspoint.com/try_angularjs_online.php

css:
http://www.tutorialspoint.com/try_css_online.php

php:
http://www.tutorialspoint.com/execute_php_online.php

php/mysql
http://www.tutorialspoint.com/php_mysql_online.php

html:
http://www.tutorialspoint.com/try_html_online.php

**Comment by ritz078** [comment]
do they support embedding ? I don't think so you can share until logged in.

**Comment by comtronix** [comment]
This one has emebed support. 

http://ideone.com/0GQY2W

**Comment by ritz078** [comment]
ideone is already supported by this plugin.

**Comment by comtronix** [comment]
i did not see that :P sorry for mention it.
