### ISSUE TITLE
Installing embed.js with meteor (meteor+react stack)

### ISSUE THREAD

**Issue by niko-h** [ritz078/embed.js#211]
I installed embedjs via `meteor npm install --save embed-js` and the module seems to be installed properly @4.1.13.
Requiring it via `import EmbedJS from 'embed-js';` does not work though. It gives me an 
> Uncaught Error: Cannot find module 'embed-js'

It is probably a meteor thing and maybe there'd be need for some wrapper package.

**Comment by ritz078** [comment]
Can you create a minimal repo with reproduction ?

**Comment by niko-h** [comment]
Hi, while creating a new repo for reproduction it now finds the module and doesnt complain any longer...also in my actual project.
No clue why this didnt work in the first place, but apparently its ok now, so no need (and also no way) to reproduce.
Thanks anyway for your attention.

**Comment by ritz078** [comment]
Glad it worked for you.
