### ISSUE TITLE
Spotify outputs error in console

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#22]
Getting error in console on spotify.,... i don't understand :(

Blocked cross- Origin application : the Same Origin Policy is reading the external source https://jxnvqvdyms.spotilocal.com:4374/service/version.json?service=remote&ref=http%3A%2F%2F........................%2Fforum%2Fmessages%2F11100&cors= not increase. (Reason: CORS request failed ) .

**Comment by ritz078** [comment]
Thats a problem with spotify's embed API. Nothing that i could do . Thats their bug to fix.
