### ISSUE TITLE
cdn broken url

### ISSUE THREAD

**Issue by kiwi1342** [ritz078/embed.js#232]
Hi, in the doc --> installation there is a CDN link but it's broken

https://embedjs.readme.io/docs/installation

**Comment by ritz078** [comment]
It seems jsdelivr is unable to take built files from npm. For the time being you can use files from cdnjs.com https://cdnjs.com/libraries/embed-js

**Comment by kiwi1342** [comment]
thanks, unfortunately there are some issues with the latest version. I'll fill another issue...

**Comment by ritz078** [comment]
Sure.
