### ISSUE TITLE
Uncaught TypeError: Cannot set property 'LANGUAGES' of undefined

### ISSUE THREAD

**Issue by kiwi1342** [ritz078/embed.js#233]
With the latest version (4.2.1) I keep getting the the following error when initialising the class:

    Uncaught TypeError: Cannot set property 'LANGUAGES' of undefined

This happens with any embed source

**Comment by ritz078** [comment]
Can you create a codepen demo ?

**Comment by kiwi1342** [comment]
Apparently is something that happens if loading the file through the browser console. I cannot replicate it loading the source normally.

**Comment by ritz078** [comment]
Well if its working well normally it shouldn't be a problem :) Let me know if it is.
