### ISSUE TITLE
Unexpected token export loading embed.es2015.js

### ISSUE THREAD

**Issue by kiwi1342** [ritz078/embed.js#237]
Loading the embed.es2015.js source it returns the following error

embed.es2015.js:1795 Uncaught SyntaxError: Unexpected token export

You can see the error in console using the following fiddle:

https://jsfiddle.net/be86syoe/

**Comment by ritz078** [comment]
It won't run until you build it using soemthing like webpack. You will have to ES5 version `embed.js` to run in jsfiddle.

**Comment by kiwi1342** [comment]
You are right, my bad, sorry.
