### ISSUE TITLE
Twitter embed requires widgets.js

### ISSUE THREAD

**Issue by kiwi1342** [ritz078/embed.js#239]
You should state in the doc that to implement a Tweet embed first you should have the widgets.js coming from the Twitter platform otherwise it won't work. Wouldn't it be possible to include it in the source file?

**Comment by ritz078** [comment]
It is documented https://embedjs.readme.io/docs/options#section-tweetsembed
Can't include in the main bundle as that will increase filesize for people who don't want to use that feature.
