### ISSUE TITLE
How to unset/unload Embed.js

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#24]
I want to enable/disable the Embed.js function on a div (by clicking a button) for use in a box to show source or preview output.

Is there a way to unload/disable the function ?

**Comment by ritz078** [comment]
Currently there's no such feature.

**Comment by comtronix** [comment]
Topic change: Request function :)

**Comment by ritz078** [comment]
I don't think its possible to unload as i am not storing the original text and actually modifying the original text. Though loading a block is in my mind for the next version :)

**Comment by comtronix** [comment]
Hope the option for loading a block can be available soon :)

**Comment by ritz078** [comment]
it has come too soon :+1: test it so that i can merge all the new changes to master.

**Comment by comtronix** [comment]
** test **

**Comment by comtronix** [comment]
Thnx! i use the following to get the value of the WRITE area (like this editor here on Github) i have also a tab called Preview. Whe i click the tab, the EmbedBlock must be called but it only works on 1th click. New changes are not  converted. 

Am i using the -your-  function as suposed to be?

```
$('#prevClick').click(function(){

    // convert linebreaks            
    var div = $("#preview")[0];
    var lines = $("#comment").val().replace(/\r\n/g, "\n").split("\n");
    for (var i = 0, len = lines.length; i < len; ++i) {
        if (i) div.appendChild(document.createElement("br"));
        div.appendChild(document.createTextNode(lines[i]));
    } 
    
    $('.preview_box').embedBlock({
        // options
    });

});
```

**Comment by ritz078** [comment]
can't understand until i see the whole code.

**Comment by comtronix** [comment]
code updated

**Comment by ritz078** [comment]
it will be better if you create a [jsfiddle](http://jsfiddle.net/)

**Comment by comtronix** [comment]
http://jsfiddle.net/50a7kwp5/2/

**Comment by ritz078** [comment]
If you aren't setting anything in **gDevAuthKey** , you have disable videoEmbed
```html
<html>
<textarea id="comment" rows="8"></textarea>
<div id="preview"></div>
<button type="button" id="prevClick">preview</button>
</html>

<script>

$('#prevClick').click(function(){

    $("#preview").empty();

    // convert linebreaks            
    var div = $("#preview")[0];
    var lines = $("#comment").val().replace(/\r\n/g, "\n").split("\n");
    for (var i = 0, len = lines.length; i < len; ++i) {
        if (i) div.appendChild(document.createElement("br"));
        div.appendChild(document.createTextNode(lines[i]));
    } 

    $('#preview').embedBlock({
        videoEmbed:false  //setting videoembed to false ... if you enable it , you will have to set //gDevAuthKey
    });

});
</script>
```

**Comment by comtronix** [comment]
http://jsfiddle.net/50a7kwp5/9/

@ comment for you:)

**Comment by ritz078** [comment]
check now :)

**Comment by comtronix** [comment]
found a bug , sorry :)

http://jsfiddle.net/50a7kwp5/20/

al DOC items are in 1 Doc box.

**Comment by ritz078** [comment]
thats because you have replaced newline with <br>
your string becomes ```http://open.spotify.com/track/4th1RQAelzqgY7wL53UGQt<br>https://www.cca.edu/sites/default/files/pdf/08/word-to-pdf.pdf``` if there is a space or a normal newline character this bug won't happen.

**Comment by ritz078** [comment]
i have fixed that. now that should be fine. Please make a new issue for each bug. Its easy to track.

**Comment by comtronix** [comment]
Thanx! updated my code. it works fine on doc now. Posting new issues in new topic :)
