### ISSUE TITLE
how to embed facebook posts

### ISSUE THREAD

**Issue by kiwi1342** [ritz078/embed.js#240]
I saw there was a pull request now closed for fb embedding

https://github.com/ritz078/embed.js/pull/229

I was wondering how to embed them. No info on the doc and adding a simple URL won't work

**Comment by ritz078** [comment]
@sohamidha

**Comment by SnehaMidha** [comment]
See this http://codepen.io/SnehaMidha/pen/evQpGX

**Comment by ritz078** [comment]
https://embedjs.readme.io/docs/facebook-demo
