### ISSUE TITLE
Cant import .css from dist with Webpack

### ISSUE THREAD

**Issue by hazzo** [ritz078/embed.js#245]
Hi, I am having some trouble to import the css file to a Vue app (with Quasar Framework) that I'm working on.

I'am importing it this way: `@import "~embed-js/dist/embed.css"`

Here it's the error that I am getting:

```
./~/css-loader?sourceMap!./~/embed-js/dist/embed.css
Module not found: Error: Can't resolve './assets/images'
```

Thanks!

**Comment by ritz078** [comment]
Are you on the latest version. i.e 4.2.3 ?

**Comment by hazzo** [comment]
Yes on that exact version.

**Comment by ritz078** [comment]
Its working for me.

- Do you have a loader for png files in your webpack config ?
- Can you uninstall and reinstall embed-js and confirm ?

I checked the files and they are present there.

is https://cdnjs.cloudflare.com/ajax/libs/embed-js/4.2.3/embed.css working ?

**Comment by hazzo** [comment]
Yes with the cdn option is working. The framework I'm using has a loader for webpack. I will try to reinstall and give a feedback.

**Comment by ritz078** [comment]
Is the code available anywhere ?

**Comment by hazzo** [comment]
Not my project sorry :S, but I can give you the link of the frameworks repo: [https://github.com/quasarframework/quasar/tree/v0.13/build](url)

**Comment by ritz078** [comment]
you may be working on a fork or a branch. If I can see that maybe I can help ?

I don't see any problem with the module as every file is present at the place it should be.

**Comment by hazzo** [comment]
Sorry the link I gave you isn't working, try this one: https://github.com/quasarframework/quasar

**Comment by ritz078** [comment]
Hi @hazzo ,

As far as the CSS file is present in the dist directory, I am sure this is an error with the webpack config.

**Comment by hazzo** [comment]
Sorry but I couldn't make it work. I opted for using Unicode emojis. Thanks!
