### ISSUE TITLE
Link break in FB posts

### ISSUE THREAD

**Issue by d8vjork** [ritz078/embed.js#248]
![image](https://user-images.githubusercontent.com/2331052/28939476-b9cb1040-7891-11e7-84c8-a351a63e4b8a.png)

As can see in the screenshot, it take the previous link with <a> tag and it fail because of ".

**Comment by ritz078** [comment]
Can you give me the whole URL that was wrongly processed ?

**Comment by d8vjork** [comment]
@ritz078 Yep, of course: https://www.facebook.com/socialchan.sn/posts/1388246151263048

**Comment by d8vjork** [comment]
PD: I check with the example URL of the documentation (https://www.facebook.com/madovermarketing/posts/1402165223182741), and same failure.

That's my EmbedJS config:

```
window.embedjs.setOptions({
    marked              : false,
    emoji               : false,
    fontIcons           : false,
    link                : true,
    linkOptions         : {
        target          : 'blank',
    },
    tweetsEmbed         : true,
    tweetOptions        : {
        maxWidth        : 550,
        align           : 'center',
    },
    googleAuthKey       : '..........',
    singleEmbed         : true,
    videoWidth          : 720,
    inlineEmbed         : 'all',
    soundCloudOptions   : {
        height          : 200,
    },
});
```

**Comment by ritz078** [comment]
It seems that's a bug.

**Comment by ritz078** [comment]
Do you only need facebook embedding ?

**Comment by d8vjork** [comment]
No, I need full embedding

**Comment by ritz078** [comment]
You can try the new v5 beta. Here is the demo https://codesandbox.io/s/Wp5OlNMn

**Comment by d8vjork** [comment]
Yeah, now yes, thank so much @ritz078!

PD: I'll make some contributions (if I can) and a donation for the project :+1:
