### ISSUE TITLE
Optional: css for small devices.

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#25]
@media only screen and (min-width: 480px) and (max-width: 767px) { 
    .ejs-doc-icon {
        border-right: 0px solid #eee;
        height: 110px;
        width: 200px;
    }    
    .ejs-doc-icon i {
        margin: 15px 148px;
    }
    .ejs-doc-view{
        height: 65px;
        width: 366px;
        text-align: center;
    }
    .ejs-doc-view button {
        float: none;
        margin: 10px 10px 0;
        padding: 6px 15px;
    }
    .ejs-doc-viewer {
        height:320px;
    }
    .ejs-doc-title {
        display: none;
    }
    .ejs-doc-detail {
        padding-left: 0px;
        width: 180px;
    } 
    .ejs-doc {
        margin: 20px 0;
        overflow: auto;
    }
    .ejs-video-detail {
        display: none;
    }
    .ejs-video-title {
        display;none;
    }
    .ejs-video-desc {
        display: none;
    }
    .ejs-stats {
        display: none;
    }
    .ejs-video-stats span {
        display: none;
    }
    .ejs-video-stats span i {
        display: none;
    }
    .ejs-video-preview img {
        height: 224px;
        width: 348px;
    }
    .ejs-video-thumb {
        float: none;
        width: 348px;
    }
    .ejs-video-thumb i {
        margin-left: 160px;
        margin-top: -128px;
    }    
}

@media only screen and (max-width: 479px) { 
    .ejs-doc-icon {
        border-right: 0px solid #eee;
        height: 110px;
        width: 228px;
    }    
    .ejs-doc-icon i {
        margin: 15px 78px;
    }
    .ejs-doc-view{
        height: 100px;
        width: 228px;
        text-align: center;
    }
    .ejs-doc-view button {
        float: none;
        margin: 10px 10px 0;
        padding: 6px 15px;
    }
    .ejs-doc-viewer {
        height:320px;
    }
    .ejs-doc-title {
        display: none;
    }
    .ejs-doc-detail {
        padding-left: 0px;
        width: 180px;
    } 
    .ejs-doc {
        margin: 20px 0;
        overflow: auto;
        /*
        overflow-y:hidden;
        overflow-x:hidden;
        */
    }    
    .ejs-video-detail {
        display: none;
    }
    .ejs-video-title {
        display;none;
    }
    .ejs-video-desc {
        display: none;
    }
    .ejs-stats {
        display: none;
    }
    .ejs-video-stats span {
        display: none;
    }
    .ejs-video-stats span i {
        display: none;
    }
    .ejs-video-player {
        width: 208px;
        overflow:auto;
    }
    .ejs-video-player iframe {
        width: 208px;
    } 
    .ejs-video-preview img {
        height: 138px;
        width: 208px;
    }
    .ejs-video-thumb {
        float: none;
        width: 208px;
    }
}

**Comment by ritz078** [comment]
can you post the screenshot of the output ?

**Comment by comtronix** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/3840400/7221143/83c30c4a-e6e0-11e4-829b-e122ac77dcaf.png)
