### ISSUE TITLE
Fail compiling with Webpack (production env)

### ISSUE THREAD

**Issue by d8vjork** [ritz078/embed.js#254]
![image](https://user-images.githubusercontent.com/2331052/29915296-abb0f01e-8e3b-11e7-80d0-807fa2d37d10.png)

https://github.com/ritz078/embed-js/blob/0db7d39597f659768b42adca06c12a854a8c0adc/packages/embed-plugin-utilities/src/insert.js#L7

**Comment by ritz078** [comment]
UglifyJS has problems with understanding ES6 code. Try https://github.com/webpack-contrib/babel-minify-webpack-plugin instead of uglifyJS

**Comment by d8vjork** [comment]
Ok, I'll try next build, thank you so much @ritz078

**Comment by ritz078** [comment]
Is there still an issue ?

**Comment by d8vjork** [comment]
Nop, solved! :+1:
