### ISSUE TITLE
Ordering items

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#26]
When posting a list of items the output is not in same order. It would be nice(r) and logical if embed shows are in same direction/list.

https://www.cca.edu/sites/default/files/pdf/08/word-to-pdf.pdf
https://twitter.com/MarjoleinPloegm/status/586461330980343808
https://www.youtube.com/watch?v=QHulaj5ZxbI
http://jsbin.com/iwovaj/73

http://jsfiddle.net/50a7kwp5/26/

**Comment by ritz078** [comment]
this one is tricky.

**Comment by ritz078** [comment]
@jesusprubio any suggestions regarding this ?

**Comment by comtronix** [comment]
Tricky function request? :)

**Comment by ritz078** [comment]
yes but i am try to rewrite some functionalities that will help in fixing this issue.

**Comment by comtronix** [comment]
thnx

**Comment by comtronix** [comment]
When i post Google docs items:

http://www.vorsite.nl/content/bestanden/samenvatting-evers_brouwers_etc_2001_03.doc
http://www.econ.yale.edu/~shiller/data/ie_data.xls
https://www.cca.edu/sites/default/files/pdf/08/word-to-pdf.pdf
http://ideone.com/0GQY2W

this happens:
![11](https://cloud.githubusercontent.com/assets/3840400/7489794/00b0be9e-f3db-11e4-8712-ab0c0f9e08f6.png)

in previous version it was:
![12](https://cloud.githubusercontent.com/assets/3840400/7489845/4f738976-f3db-11e4-8b2f-94238e659f6a.png)

**Comment by ritz078** [comment]
the current regex is ```/((?:https?):\/\/\S*\.(?:pdf|doc|docx|xls|xlsx|ppt|pptx))/gi``` Currently S* accepts \n, \r and spaces also.Just working on a regex that excludes those. If you have any suggestion, do comment.
