### ISSUE TITLE
bug found multiple images (embedBlock)

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#31]
In embedblock images are not displayed when posting more than 1 of the same link.

http://jsfiddle.net/50a7kwp5/35/

**Comment by ritz078** [comment]
duplicates will not be visible. thats intentional.

**Comment by comtronix** [comment]
i know. but 2 links are the same image. the 3e is differten link. the 3e image is not showing.

**Comment by comtronix** [comment]
Updated the fiddle http://jsfiddle.net/50a7kwp5/36/

**Comment by ritz078** [comment]
this is a duplicate of #28 . It has already been solved in the latest commit.

**Comment by comtronix** [comment]
But that's the weird thing: i am using the latest build..

http://jsfiddle.net/50a7kwp5/37/

**Comment by ritz078** [comment]
Please use codepen instead of jsfiddle :)

**Comment by ritz078** [comment]
All these problems arise because you are replacing newline with ```<br>``` so the string presented to embedJS is ```@(IIT Roorkee)<br>same:<br>http://static1.ad.nl/static/photo/2015/10/14/5/20150419232616/media_l_2922875.jpg<br>http://static1.ad.nl/static/photo/2015/10/14/5/20150419232616/media_l_2922875.jpg<br>new:<br>http://static2.ad.nl/static/photo/2015/16/13/2/20150419223816/media_l_2923622.jpg<br>``` and all appears as a single word.

**Comment by ritz078** [comment]
here's the blunder:
by default **imageEmbed** is set to **false** . Set it to true.

**Comment by ritz078** [comment]
fixed

**Comment by comtronix** [comment]
Yess! You did it !
