### ISSUE TITLE
Function request: Flickr support

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#32]
Request Flickr embed support.

**Comment by ritz078** [comment]
Hey @comtronix ,
Can you make a new issue with mentioning how the Readme (documentation) can be improved. I understand that its a bit complex now and would like to get your views regarding that so that it makes sense to someone reading at the first time.

**Comment by comtronix** [comment]
I will give it a try. My english is not so good,  I'll read your current document asap and add post suggestions.

**Comment by comtronix** [comment]
thanx btw for the latest updates

**Comment by ritz078** [comment]
Don't worry about the english . just suggest the content modifications. I will do it.
