### ISSUE TITLE
Doc enhance

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#38]
Maybey the options list can be styled like this example:

https://github.com/glarios/fbPhotoStream#options

**Comment by comtronix** [comment]
Add info how to create API key for GoogleMap.
https://github.com/ritz078/embed.js/issues/37

**Comment by ritz078** [comment]
@comtronix Thats a nice method when you have less number of options and they are in flat structure like ```javascript
{
 optionA:value,
 optionB:value,
 optionC:value
}
```
but it really gets confusing when nested objects are used in options like
```javascript
{
 optionA:value,
 optionB:{
     optionC:value,
     optionD:value
 }
}
```
This plugin has has nested options and those are really important .
To make sure no confusions arise, I chose this way where everything is crystal clear.

**Comment by ritz078** [comment]
Any good resource demonstrating how to obtain api key .Will just provide the link to it.

**Comment by comtronix** [comment]
https://developers.google.com/api-client-library/python/guide/aaa_apikeys

**Comment by ritz078** [comment]
added the link so no need of sending a PR :)
