### ISSUE TITLE
FlickR noflick

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#41]
Do you know what this is with the FlickR images and EMBEDjs?

http://www.flickr.com/photos/98263296@N03/11691666724/
http://www.flickr.com/photos/98263296@N03/11691666724/
, no Flickr http://www.flickr.com/photos/98263296@N03/11733196833/
http://www.flickr.com/photos/98263296@N03/11733196833/
, no Flickr

![knipsel](https://cloud.githubusercontent.com/assets/3840400/7656197/5ce8717a-fb29-11e4-9bf1-452398111ef3.PNG)

**Comment by ritz078** [comment]
raw text ?

**Comment by comtronix** [comment]
this is what is posted/used

http://www.flickr.com/photos/98263296@N03/11691666724/
http://www.flickr.com/photos/98263296@N03/11691666724/
http://www.flickr.com/photos/98263296@N03/11733196833/
http://www.flickr.com/photos/98263296@N03/11733196833/

**Comment by comtronix** [comment]
Thank you! it's working fine now!
