### ISSUE TITLE
Use noto-emoji in embed.js

### ISSUE THREAD

**Issue by wurik** [ritz078/embed.js#46]
Hi, I see that all emojis are in one file and I can't find the way to use the noto-emojis ( https://github.com/googlei18n/noto-emoji ). 
Thanks for this great work and for all !

**Comment by ritz078** [comment]
Hi @wurik ,
In the next version, i.e v3.0.0 you can add your image and create a custom sprite that can be used as an emoji.

**Comment by wurik** [comment]
Hi @ritz078 thanks for your answer ! Great news !
But do you know how I can generate a sprite that works for the actual version ?

**Comment by ritz078** [comment]
If you wan't to use it now you will have to use the in-dev version [here](https://github.com/ritz078/embed.js/tree/es6)
