### ISSUE TITLE
More plugins support?

### ISSUE THREAD

**Issue by lajpatshah** [ritz078/embed.js#52]
Sincere thanks for making this plugin. Its awesome.
Are you planning on including following plugins? 
1) Instagram
2) Slideshares
3) TED

**Comment by ritz078** [comment]
Instagram and ted are already supported. I will see if Slideshare can be supported.

**Comment by lajpatshah** [comment]
Sorry my bad yes TED is there but in your example list instagram is not mentioned

thanks though

**Comment by ritz078** [comment]
Slideshare is now supported.

**Comment by lajpatshah** [comment]
thank you sir
