### ISSUE TITLE
Bower install failing?

### ISSUE THREAD

**Issue by causztic** [ritz078/embed.js#59]
am having this message when im attempting to install with bower:

bower embed-js#*            
EMALFORMED Failed to read /var/folders/xh/mzwpjt1d3bgg6wmsvkwsq9f40000gn/T/user/bower/264d16b7d819bc21408de67ee21d81bb-15037-5F7sQ7/bower.json

Additional error details:
Unexpected token ]

Any ideas?

**Comment by ritz078** [comment]
fixed in v3.0.2

**Comment by causztic** [comment]
thanks!
