### ISSUE TITLE
Can't get ejs method working with .applyEmbedJS()

### ISSUE THREAD

**Issue by peterph-am** [ritz078/embed.js#64]
I want to embed some code highlighting on a style guide I'm building.

I've got these in my head: 

```html
<link rel="stylesheet" type="text/css" href="https://rawgit.com/ritz078/embed.js/es6/dist/embed.min.css" />
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/github.min.css" />
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" />
```

and this after my body:

```js
<script src="http://platform.twitter.com/widgets.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/highlight.min.js"></script>
<script src="https://rawgit.com/ritz078/embed.js/master/dist/embed.min.js"></script>
<script type="text/javascript">
	ejs.setOptions({
		highlightCode: true
	});

	ejs.applyEmbedJS('.u-ui-pre');
</script>
```

But I'm not getting the highlighting rendering.

Am I using it wrong? This should be in the examples section I feel.

**Comment by ritz078** [comment]
Hi @peterph-am ,

just use
```js
ejs.applyEmbedJS('u-ui-pre')
```
Note that there's no `.` in the class name but i agree that even this should be acceptable so will be adding it now . I will also add an example related to this. Thanks for pointing it out :+1:

**Comment by ritz078** [comment]
Now (in v3.3.2) it will even work with the `.`

**Comment by peterph-am** [comment]
Ahhh I see! Cool thanks for the speedy reply & fix
