### ISSUE TITLE
Error message on .render()

### ISSUE THREAD

**Issue by Mat-thieu** [ritz078/embed.js#65]
Hello,

I've been trying to get your plugin to work, but every time I attempt to render I get this error message;

```javascript
Uncaught (in promise) ReferenceError: hljs is not defined(…)                 embed.min.js:10
```

I've installed via npm and loading the minified version from /dist
I've also tried a CDN and I tried to load from /src but the same error keeps coming back.

**Comment by ritz078** [comment]
Earlier `highlightCode` was set to true by default so it need highlight.js . Now its fixed and set to `false` by default. If you set it to true you will have to load [highlight.js](https://highlightjs.org/) to enable code highlighting.
