### ISSUE TITLE
Using Embed.js with input forms (and live preview)

### ISSUE THREAD

**Issue by BoweFrankema** [ritz078/embed.js#68]
Hi Ritesh,

Awesome work on this plugin, it seems very promising. I was wondering if you could add an example or some directions on how to initialise embed.js on a input form. Think of a Status Update ala Facebook or any form that takes direct input.

In an ideal situation embed.js would be attached to a input form and would show a live preview as the user types/pastes media/links/videos. 

Thanks in advance for your help :-)

**Comment by ritz078** [comment]
On it :+1:

**Comment by BoweFrankema** [comment]
![](http://replygif.net/i/603.gif)

**Comment by ritz078** [comment]
This will need some major changes in the plugin so i am adding it as an enhancement.

**Comment by irazasyed** [comment]
+1 :+1:

**Comment by ritz078** [comment]
This feature will be a huge addition to the current file size. I will wait to see if that would be feasible. If I find in future that this is needed by lot of users then will come back to this. Till then I am closing the issue. I will keep an eye on this though. I had this in v4 milestone but while developing i realized that this will add significant size to the existing plugin.

Maybe I will try to develop this as an extension to current plugin.
