### ISSUE TITLE
Multiple YouTube Videos

### ISSUE THREAD

**Issue by enesemini** [ritz078/embed.js#76]
Hey there,

first of all, embed.js is awesome und super easy to use. Thanks for that.

I have come across one issue though. Whenever I have multiple YouTube video embeds, and I click one to view the video, all the others stop working. What I mean is that you can't click another video to view right in the browser.

Is this supposed to be like this? Is there any way around this, or is this a bug?

You can see what I mean in this example:
http://codepen.io/ritz078/pen/JYmJML

Click the first video, and then click the second video. In my case at least, the second video won't play.

Thanks for your effort.

Kind regards

**Comment by ritz078** [comment]
Hi @enesemini ,

Thanks for your kind words and reporting this. Its a bug. I am on it :+1:

**Comment by soufiaane** [comment]
wrong person

2015-12-25 21:48 GMT+00:00 Ritesh Kumar <notifications@github.com>:

**Comment by ritz078** [comment]
Hi @soufiaane . You received the mail because you are watching this repo. Just unwatch it and your problem will be solved.

**Comment by ritz078** [comment]
Hi @enesemini . I have fixed it. update the plugin to check it. Let me know if there is any other problem.

**Comment by enesemini** [comment]
Hi @ritz078 

Thank you very much! Awesome support! I definitely will, whenever I find something.

Have a good day!
