### ISSUE TITLE
Add OG Parsing?

### ISSUE THREAD

**Issue by irazasyed** [ritz078/embed.js#82]
Can we have Open Graph parsing added?

Basically, What facebook does. So if the link has the OG tags, it'll extract all the details and show a preview of the link (only for the first link ofc). Would make this whole embedjs a complete package.

Edit: Check out for more details - http://ogp.me/

**Comment by ritz078** [comment]
As far as i understand, you need a server due to the cross domain restrictions for that. The alternatives are : 
* Using facebook graph API. Still unsure of request limitations.
* Using [http://opengraph.io/](http://opengraph.io/) . Its paid for more than 5000 requests/month
* Give an option for creating your own server.

**Comment by irazasyed** [comment]
Yep!

I think our own server would be much better. You could setup another repo with server codes and let people setup the endpoint if they want to use OG parsing feature.

I can setup the server bootstrap for that if you'd like.

**Comment by ritz078** [comment]
I was thinking of choice between an API and server. So that even someone has small needs he doesn't have to setup his own server.

**Comment by irazasyed** [comment]
Why not support both?

Since both have to return response in json format. So if they want to use the API, they can provide the details for the same or provide an endpoint that returns the required data.

**Comment by ritz078** [comment]
Ya i am talking about that only. Support both and provide an option. I am finding a good API for this. If you have any suggestions, it will be great.

**Comment by irazasyed** [comment]
Sure, I'll post here if i could find some better APIs.

**Comment by ritz078** [comment]
Ya that will be great .

**Comment by irazasyed** [comment]
How about we use YQL - https://developer.yahoo.com/yql/ it has nice rate-limits too.

> Per application limit (identified by your Access Key): 100,000 calls per day
Per IP limits: /v1/public/*: 2,000 calls per hour; /v1/yql/*: 20,000 calls per hour

**Comment by irazasyed** [comment]
Check this out: https://github.com/nfl/jquery-oembed-all

This project uses oembeds and has a fallback which relies on open-graph protocol using YQL.

**Comment by irazasyed** [comment]
So you could add support for a ton of sites using oembeds (i can see you're using for twitter already but could support bunch of more, including WP sites) and using YQL fallback to OGP. And i think this limit is quite enough for most of us and in the event in which people still need to cross that limit, they can always provide their own endpoint which would return parsed data in JSON format.

**Comment by ritz078** [comment]
Yes i guess that will fine for Open graph. As far adding oEmbed support is concerned, I would like to add only important link embeddings. Some issues yet to be discussed are what happens in case of flick url. Do i show the site's meta data for that link or embed the image slider. Maybe an option for that too. Same case for other services like codepen, gist etc.

**Comment by irazasyed** [comment]
I would recommend you prioritize the tasks and work on these things. For now, OG support would be good since that'll support a huge number of sites and pretty much every site i think. Then later you can add support for important links using oEmbed.

**Comment by ritz078** [comment]
Those supports are already there. I am trying to figure out what happen in that case where a link is used to embed things. Eg :  

http://flickr.com/something

Embed the image slideshow or show the grap API data.

**Comment by irazasyed** [comment]
How about you have an option for that?

So for example, If the developer prefers to embed a slideshow for that site, they can do so. Otherwise by default it'll stick to OG globally for all links. Provider specific options would make sense.

**Comment by ritz078** [comment]
YQL doesn't work for lot of urls and its not maintained now. So that option is crossed.

**Comment by irazasyed** [comment]
I see. Then we're left with that opengraph.io API and custom endpoint for now.

**Comment by ritz078** [comment]
Opengraph.io needs credit card even for signup. So we are left only with custom endpoint.

**Comment by irazasyed** [comment]
But for free plan, it's open. I just tested for one URL and it returned me valid data.

**Comment by irazasyed** [comment]
It has a limit though, obviously -- 5k max.

**Comment by ritz078** [comment]
Seems thats the way to go.

**Comment by irazasyed** [comment]
Yep! You can ofc highlight it in your docs that it has a hard limit of 5k and that, it's recommended to setup your own endpoint if you're a heavy user and link back to the server side codes. Should be enough.

**Comment by ritz078** [comment]
If this doesn't work out , i am thinking of setting it up as a separate project open for all.

**Comment by irazasyed** [comment]
You mean like a plugin or something? Or a fork of this with OG support?

**Comment by irazasyed** [comment]
If you can't get that API integrated, why not just integrate custom server end point support and for now just let people switch between OG and standard embeds. Also, What you can do is, Just have OG as a fallback for all the URLs. So for example, If i don't enable gist embed, then by default it'll just show me the OG data (if that's ON in options).

**Comment by ritz078** [comment]
Ya i have already integrated opengraph.io but i was talking about a service like opengraph.io that open source.

**Comment by irazasyed** [comment]
Isn't that same thing that we already discussed?

Have a server side code in a separate repo, So people can setup their own.

If you were to host that service for people, then you know it could cost you hefty bills if you keep it open for free right?

**Comment by ritz078** [comment]
Yup will figure it out later. Now thats not the preference. Currenly integrating the server support for this plugin.

**Comment by irazasyed** [comment]
Ok!

**Comment by ritz078** [comment]
During testing i felt that the data limit on the API makes no sense as :

* limits the usage of the plugin 
* the API is not official so it also doesn't guarantee long term support. 
* many urls are returning no result
* is too slow.

I would rather want to provide full fledged server integration with options for callback and also how to handle the response. Also the check for shout url should be part of backend rather than frontend.

**Comment by irazasyed** [comment]
Those are some valid points indeed.

So i guess, we're now left with only one option?

**Comment by ritz078** [comment]
Yes.

**Comment by ritz078** [comment]
```javascript
openGraphEndpoint : 'http://127.0.0.1/${url}', // This may be even url of opengraph.io 
openGraphExclude : ['youtube', 'github'],
onOpenGraphFetch : function(data){
  // data is the response received from the server.
 // Change to proper format
 // {success:true, title:'', description:'', image:'',url:''}
}
```

**Comment by irazasyed** [comment]
Perfect :+1: 

Thanks!
