### ISSUE TITLE
host on cdnjs for easier reuse

### ISSUE THREAD

**Issue by gasolin** [ritz078/embed.js#89]
to make experiment easier on jsfiddle, it might worth to host embed.js onto https://cdnjs.com/

**Comment by ritz078** [comment]
Definitely planning to do this. Will try this soon.

**Comment by ritz078** [comment]
Currently on jsdelivr

```
https://cdn.jsdelivr.net/embed.js/3.6.0/embed.min.js

https://cdn.jsdelivr.net/embed.js/3.6.0/embed.min.css
```

will be on cdnjs soon.

**Comment by gasolin** [comment]
It's there! though I see the header version shows 3.5.0 in https://cdn.jsdelivr.net/embed.js/3.6.0/embed.min.js ;)

**Comment by ritz078** [comment]
oh that was because i didn't run the grunt release. Don't worry its updated.
